src/ProviderCustomers/Models/Domain/Site.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace ProviderCustomers.Models.Domain
{
    public class Site
    {
        [Key]
        public long Id { get; set; }
        [Required, StringLength(200)]
        public string Address { get; set; }
        [Required, StringLength(4000)]
        public string Description { get; set; }
        public int Rating { get; set; }
        public DateTime LastEdited { get; set; }
        public HostingPlan Plan { get; set; }
        public byte[] Logo { get; set; }
        public string LogoType { get; set; }

        public void SetLogo(HttpPostedFileBase file)
        {
            if (file == null || file.ContentLength <= 0) 
                return;

            Logo = new byte[file.ContentLength];
            file.InputStream.Read(Logo, 0, file.ContentLength);
            LogoType = Path.GetExtension(file.FileName);
            if (!string.IsNullOrWhiteSpace(LogoType) && LogoType.StartsWith("."))
            {
                LogoType = LogoType.Remove(0, 1);
            }
        }
    }
}

src/ProviderCustomers/Controllers/SiteController.cs
using System.Data;
using System.Linq;
using System.Web.Mvc;
using ProviderCustomers.Models;
using ProviderCustomers.Models.Domain;

namespace ProviderCustomers.Controllers
{
    public class SiteController : Controller
    {
        private readonly ProviderCustomersContext _db = new ProviderCustomersContext();

        public ActionResult Index()
        {
            return View(_db.Sites.Include("Plan").ToList().Select(s => new SiteListItemViewModel(s)).ToList());
        }

        public ActionResult Create()
        {
            SetSiteEditTitle(isNew: true);
            ViewBag.Plans = GetHostingPlans();
            return View("CreateOrEdit");
        }

        public ActionResult Logo(long id)
        {
            var site = _db.Sites.Find(id);
            if (site == null || site.Logo == null)
            {
                return HttpNotFound();
            }
            return File(site.Logo, "image/" + site.LogoType);
        }

        public ActionResult Edit(long id = 0)
        {
            var site = _db.Sites.Find(id);
            if (site == null)
            {
                return HttpNotFound();
            }
            SetSiteEditTitle(isNew: false);
            ViewBag.Plans = GetHostingPlans();
            return View("CreateOrEdit", new EditSiteViewModel(site));
        }

        [HttpPost]
        public ActionResult Save(EditSiteViewModel model)
        {
            ModelState.Remove("Id");
            var hostingPlans = _db.HostingPlans.ToList();
            if (ModelState.IsValid)
            {
                if (model.IsNew)
                {
                    var site = new Site();
                    model.SaveSite(site, hostingPlans);
                    _db.Sites.Add(site);
                }
                else
                {
                    var site = _db.Sites.Find(model.Id);
                    if (site == null)
                    {
                        ModelState.AddModelError("", "Site is not exists");
                        return Edit(model.Id);
                    }
                    model.SaveSite(site, hostingPlans);
                    _db.Entry(site).State = EntityState.Modified;
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            SetSiteEditTitle(model.IsNew);
            ViewBag.Plans = GetHostingPlans();
            return View("CreateOrEdit", model);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(long id)
        {
            var site = _db.Sites.Find(id);
            _db.Sites.Remove(site);
            _db.SaveChanges();
            return Json(new {redirectUrl = Url.Action("Index")});
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }

        private void SetSiteEditTitle(bool isNew)
        {
            ViewBag.Title = isNew ? "Create new site" : "Edit site";
        }

        private HostingPlanViewModel[] GetHostingPlans()
        {
            var plans = _db.HostingPlans.ToList();
            var empty = new[] {new HostingPlanViewModel(null, "Not specified")};
            return empty.Concat(plans.OrderBy(p => p.Name)
                                     .Select(p => new HostingPlanViewModel(p)))
                        .ToArray();
        }
    }
}

src/ProviderCustomers/Views/Site/CreateOrEdit.cshtml
@model ProviderCustomers.Models.EditSiteViewModel

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Save", "Site", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Site</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rating)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rating)
            @Html.ValidationMessageFor(model => model.Rating)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PlanId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.PlanId, new SelectList(ViewBag.Plans, "Id", "Name"))
            @Html.ValidationMessageFor(model => model.PlanId)
        </div>

        <div class="editor-label">
            <label for="Logo">Logo</label>
        </div>
        <div class="editor-field">
            <img src="@Url.Action("Logo", new {id=Model==null ? 0 : Model.Id})" alt="No logo" style="height: 100px" />
            <p>
            Select file: <input type="file" name="Logo" />
            </p>
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/ProviderCustomers/Views/Site/Delete.cshtml
@model ProviderCustomers.Models.Domain.Site

@{
    ViewBag.Title = "Delete site";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Site</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Rating)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rating)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastEdited)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastEdited)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

src/ProviderCustomers/Views/Site/Index.cshtml
@model IEnumerable<ProviderCustomers.Models.SiteListItemViewModel>

@{
    ViewBag.Title = "Site list";
}
@section css {
    @Styles.Render("~/Content/themes/base/css")
}
@section scripts {
    @Scripts.Render("~/bundles/jqueryui")

    <script type="text/javascript">

        function DeleteDialog() {
            var self = this;

            $("#delete-confirm-dialog").dialog({
                modal: true,
                autoOpen: false,
                buttons: {
                    Delete: function () {
                        $.post("@Url.Action("Delete")", {
                                id: self.id
                            }, function(response) {
                                if (response.redirectUrl) {
                                    window.location = response.redirectUrl;
                                }
                            });
                        $(this).dialog("close");
                    },
                    Cancel: function() {
                        $(this).dialog("close");
                    }
                }
            });

            self.show = function(siteId, siteName) {
                self.id = siteId;
                $("#deleting-site-name").html(siteName);
                $("#delete-confirm-dialog").dialog("open");
            };
        }

        $(function() {
            var deleteDialog = new DeleteDialog();

            $(".edit-button").button({
                icons: {
                    primary: "ui-icon-pencil"
                }
            });
            $(".delete-button").button({
                icons: {
                    primary: "ui-icon-trash"
                }
            }).click(function() {
                var siteId = $(this).attr("data-item-id");
                var siteName = $(this).attr("data-item-name");
                deleteDialog.show(siteId, siteName);
            });
        });

    </script>
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Add new site", "Create")
</p>
<table id="site-list">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Logo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlanName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastEdited)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                <img src="@item.Logo" alt="No logo" style="height: 40px;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlanName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastEdited)
            </td>
            <td>
                <a class="edit-button" title="Edit" href="@Url.Action("Edit", new { id=item.Id })">Edit</a>
                <button class="delete-button" title="Delete" data-item-id="@item.Id" data-item-name="@item.Address">Delete</button>
            </td>
        </tr>
    }
</table>

<div id="delete-confirm-dialog" title="Create new user">
    Are you sure you want to delete the site <span id="deleting-site-name"></span>?
</div>